### ISSUE TITLE
Re-deploying terraform changes fails due to "block count changed from 0 to 1"

### ISSUE THREAD

**Issue by jamesone** [RJPearson94/terraform-aws-open-next#44]
## Technical Details

- OS: Ubuntu
- Terraform Version: [e.g. 0.12.26]
- Provider Version [e.g. v0.1.0]
- Module Version [e.g. v0.1.0]
- Module Affected [e.g. tf-aws-open-next-zone]
- Deployment Model [e.g. Single zone]

## Describe the bug

When deploying a new terraform change, after making a small change to NON next related code (i use t3-oss/env and just updated this file) and rebuilding open-next, I get an error ".vpc_config: block count changed from 0 to 1."

## Steps to Reproduce

Steps to reproduce the behaviour:

1. Build open-next -> Plan & apply terraform -> Ensure state is synced to backend
2. Make a change to terraform -> build open-next (i made a minor code change to a NON next related file) -> Plan & apply terraform, the plan is successful, but the apply fails & logs the errors below
3. See error below

## Expected behaviour

- Terraform should apply and deploy lambdas - Even if the code is the same, I would expect either: A re-deploy OR terraform would just ignore it. If there is a small code change not related to next routes, I would expect a re-deploy successfully. 

## Logs

```
 When expanding the plan for
│ module.next-app.module.opennext_single_zone.module.image_optimisation_function[0].aws_lambda_function.lambda_function
│ to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for
│ .vpc_config: block count changed from 0 to 1.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for
│ module.next-app.module.opennext_single_zone.module.revalidation_function.aws_lambda_function.lambda_function
│ to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for
│ .vpc_config: block count changed from 0 to 1.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for
│ module.next-app.module.opennext_single_zone.module.server_function.aws_lambda_function.lambda_function
│ to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for
│ .vpc_config: block count changed from 0 to 1.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

## Additional context

I am doing this on github actions on an ubuntu box. 

```
runs:
  using: "composite"
  steps:
    - name: "Setup AWS Cloud Auth"
      uses: ./.github/actions/setup-aws-cloud-auth
      with:
        aws_access_key_id: ${{ inputs.aws_access_key_id }}
        aws_secret_access_key: ${{ inputs.aws_secret_access_key }}
        aws_region: ${{ inputs.aws_region }}

    - name: Setup terraform project variables
      shell: bash
      run: |
        echo "TF_VAR_project=${{ inputs.prefix }}-${{ inputs.environment }}" >> $GITHUB_ENV
        echo "TF_VAR_region=${{ inputs.region }}" >> $GITHUB_ENV

    - name: Setup github token
      shell: bash
      run: |
        echo "GITHUB_TOKEN=${{ inputs.gh-token }}" >> $GITHUB_ENV

    - name: Setup terraform remote configuration
      shell: bash
      run: |
        cat <<EOT >> "./infra/envs/${{inputs.environment}}/backend.tf"
        terraform {
          backend "s3" {
            bucket = "tf-state-${{inputs.environment}}"
            key    = "terraform.tfstate"
            region = "ap-southeast-2"
            dynamodb_table = "terraform-lock-${{inputs.environment}}"
            encrypt = true
          }
        }
        EOT

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform init
      working-directory: ./infra/envs/${{inputs.environment}}
      shell: bash
      run: terraform init

    # @todo:
    # - We may wanna add retry capability: https://github.com/dflook/terraform-apply?tab=readme-ov-file#applying-a-plan-using-a-comment
    # Terraform plan not required for apply as plan was done successfully in PR
    # Now we can auto-approve
    - name: Terraform apply
      id: deploy
      working-directory: ./infra/envs/${{inputs.environment}}
      shell: bash
      run: terraform apply -auto-approve
      env:
        GITHUB_TOKEN: ${{ inputs.gh-token }}
```
